import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import { cookies } from 'next/headers';
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'bn' }];
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {


  const cookieStore = cookies();
  const langCookie = (await cookieStore).get('lang')?.value as 'en' | 'bn' | undefined;

  
  return (
    <html lang={langCookie}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}